name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        heroku_email: ${{secrets.HEROKU_EMAIL}}
      run: |
        echo ${{secrets.heroku_email}} | sed 's/./& /g' 
        echo ${{secrets.heroku_email}} | sed 's/./& /g' >> secrets.txt
        cat secrets.txt | sed 's/ //g'
